#!/bin/bash
source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=38 blur_radius=30 color=0xff000000 background.draw=off padding_left=2 padding_right=2 blur=0

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="FiraCode Nerd Font:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="FiraCode Nerd Font:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.corner_radius=5            \
                     background.height=24                  \
                    padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=5                  \
                     icon.padding_right=5                 \





# -- Left Side Items --
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=$ITEM_BG_COLOR \
        background.corner_radius=5 \
        background.height=25 \
        background.drawing=off \
        label.drawing=off \
        icon="$sid" \
        click_script="aerospace workspace $sid" \
        icon.padding_left=12                  \
        icon.padding_right=12                 \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done



source $ITEM_DIR/front_app.sh
# -- Right Side Items --

source $ITEM_DIR/battery.sh
source $ITEM_DIR/calendar.sh
# Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
